---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxa
  namespace: default
  labels:
    app: boxa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boxa
  template:
    metadata:
      labels:
        app: boxa
    spec:
      containers:
        - name: apache
          image: httpd:2.4
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: boxa-svc
  namespace: default
spec:
  selector:
    app: boxa
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boxa
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: boxa.int.sebastine.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boxa-svc
                port:
                  number: 80
# Uncomment and configure TLS if you have a secret
  tls:
    - hosts:
        - boxa.int.sebastine.ng
      secretName: int-wildcard


---


#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: boxa-cert
#  namespace: default
#spec:
  # Secret names are always required.
#  secretName: boxa-tls
#  issuerRef:
#    name: cloudflare
#    kind: ClusterIssuer
#  dnsNames:
#    - boxa.int.sebastine.ng
