apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ui
  namespace: sec00
  labels:
    app: vault-ui
spec:
  ingressClassName: traefik
  rules:
    - host: vault.int.sebastine.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-ui
                port:
                  number: 8200
  tls:
    - hosts:
        - vault.int.sebastine.ng
      secretName: int-wildcard
